application/blueprints/radios_page.py
from flask import Blueprint, render_template
from application.db_models.radio_db import Radio

radios_page = Blueprint('radios', __name__,
                        template_folder='templates')

# For each blueprint can be separate folder with it's resources
# they can be easily get like this:
# with radios_page.open_resource('static/style.css') as f:
#     code = f.read()

# admin = Blueprint('admin', __name__, static_folder='static')
# url_for('admin.static', filename='style.css')

@radios_page.route('/radios')
def radios_list():
    Radio_model = Radio()
    radios_json = Radio_model.export_all_radios_data_to_json()
    return render_template('radios_list.html', radios=radios_json)

application/templates/parts/header_close.html
</head>
<body>

application/templates/parts/header_open.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/css/main.css">
    <script type="text/javascript" src="../static/js/jquery-3.5.1.slim.min.js"></script>
    <script type="text/javascript" src="../static/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="../static/js/popper.min.js"></script>
</head>
<body>

application/templates/parts/loader.html
<link rel="stylesheet" href="../static/css/loader.css">

<div class="spinner template" style="display:none; margin:auto">
    <div class="bounce1"></div>
    <div class="bounce2"></div>
    <div class="bounce3"></div>
</div>

application/templates/parts/login_as.html
<div class="col-3 my-1" style="text-align: end">
     {% if session['oauth'] %}
          <a class="btn btn-outline-secondary my-sm-0 mr-2" href="{{ url_for('user_settings.show_settings') }}">Settings</a>
          <a class="btn btn-outline-secondary my-sm-0 mr-2 " href="{{ session['ms_user']['uri'] }}">
               Logged as {{ session['ms_user']['display_name'] }}
          </a>
     {% else %}
          <a class="btn btn-outline-secondary my-sm-0 mr-2"
             href="{{ url_for('oauth.spotify_redirect') }}" >Log Spotify</a>
          <a class="btn btn-outline-secondary my-sm-0 mr-2"
              href="{{ url_for('oauth.deezer_redirect') }}" >Log Deezer</a>
     {% endif %}
</div>

application/templates/parts/navbar_close.html
  </nav>
</div>

application/templates/parts/navbar_menu_close.html
        </div>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark ">
<!--        <nav class="navbar navbar-light" style="background-color: #e3f2fd;">-->
    <div class="col-9">
    <button class="navbar-toggler my-1 shadow-none" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
      <a class="navbar-brand mt-1 ml-3" style="position: absolute">Online Radio proj.</a>

    </div>

application/templates/parts/navbar_menu_open.html
<div class="fixed-top mainNav">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-2">
<!--        <div class=" p-2" style="background-color: #e3f2fd;">-->
        <div class="row justify-content-between">
        <div class="col-9 my-1 pl-4">
            <a class="btn btn-outline-secondary my-sm-0"
               href="{{ url_for('radios.radios_list') }}">Radios</a>

            <a class="btn btn-outline-secondary my-sm-0"
               href="{{ url_for('tracks.tracks_list') }}">Tracks</a>

            <a class="btn btn-outline-secondary my-sm-0"
               href="{{ url_for('artists.artists_list') }}">Artists</a>

            <a class="btn btn-outline-secondary my-sm-0" >Spotify Albums</a>

            <a class="btn btn-outline-secondary my-sm-0"
                href="{{ url_for('imports.imports_list') }}">Tracks Imports</a>

            <a class="btn btn-outline-secondary my-sm-0"
                href="{{ url_for('exports.exports_list') }}">Tracks Exports</a>

            <a class="btn btn-outline-secondary my-sm-0"
               href="{{ url_for('statistics.statistics_graphs') }}">Statistics</a>
        </div>

application/templates/parts/navbar_search.html
<form class="form-inline my-2 my-lg-0">
  <input id="liveSearch" class="form-control my-1 mr-sm-2" type="search" placeholder="Start to type, let's see..." aria-label="Search">
</form>

application/templates/parts/navbar_search_close.html
<input id="liveSearch" class="form-control mx-2" style="max-width: 200px; " type="search" placeholder="Start to type, let's see..." aria-label="Search">
</form>

application/templates/parts/navbar_search_open.html
<form class="form-inline my-2 my-lg-0 col-3 d-flex justify-content-end">

application/templates/parts/pagination.html
<div class="pagination fixed-bottom justify-content-between mx-3">

  <nav aria-label="Page navigation example justify-content-end">
<!--    <ul id='pageSelect' class="pagination pagination-dark justify-content-start">-->
    <ul id='{{ pageSelect_id }}' class="pagination pagination-dark justify-content-start page-select">
      <li class="prevPage page-item disabled"><a class="back-next page-link"><--</a>
      <li class="page-item active"><a class="page firstPage page-link">1</a></li>
      <li class="page-item"><a class="page page-link">2</a></li>
      <li class="page-item"><a class="page borderPage page-link">3</a></li>
<!--      <li class="page-item disabled"><a class="lastPage page-link">from <span id="totalPages">0</span></a></li>-->
      <li class="page-item disabled"><a class="lastPage page-link">from <span class="total-pages" id="{{ totalPages_id }}">0</span></a></li>
      <li class="nextPage page-item"><a class="back-next page-link">--></a>
      </li>
    </ul>

  </nav>
<!--    <ul id='limitSelect' class="pagination pagination-dark justify-content-start">-->
    <ul id='{{ limitSelect_id }}' class="pagination pagination-dark justify-content-start limit-select">
      <li class="page-item disabled"><a class="page-link">Per Page:</a></li>
      <li class="page-item active"><a class="page-link">15</a></li>
      <li class="page-item"><a class="page-link">30</a></li>
      <li class="page-item"><a class="page-link">50</a></li>
    </ul>

</div>